#!/bin/bash

# ANSI color codes
BOLD_YELLOW='\033[1;33m'
BOLD_RED='\033[1;31m'
RESET='\033[0m'

# Change to the directory containing git repositories
cd ~/git-repos || { echo "Directory ~/git-repos not found"; exit 1; }

# Loop over each item in the directory
for dir in */; do
    # Check if it's a directory
    if [ -d "$dir" ]; then
        # Change into the directory
        cd "$dir" || continue

        # Check if it's a git repository
        if [ -d ".git" ]; then
            echo -e "${BOLD_YELLOW}Updating repository in $dir${RESET}"
            git pull
        else
            echo -e "${BOLD_RED}$dir is not a Git repository${RESET}"
        fi

        # Change back to the parent directory
        cd ..
    fi
done